inherit_gem:
  rubocop-inst:
  - rubocop.yml

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5

Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
